services:
  postgres:
    image: postgres:15
    container_name: ares-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ares
      - POSTGRES_PASSWORD=yoursecurepassword
      - POSTGRES_DB=ares_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  n8n:
    image: n8nio/n8n
    container_name: ares-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
      - NODE_FUNCTION_ALLOW_EXTERNAL=js-yaml 
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./config:/home/node/config 
    depends_on:
      - analytics-service

  analytics-service:
    container_name: ares-analytics
    build:
      context: ./analytics-service 
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ares_db
      - SPRING_DATASOURCE_USERNAME=ares
      - SPRING_DATASOURCE_PASSWORD=yoursecurepassword
    depends_on:
      - postgres

  automation-service:
    container_name: ares-automation
    build:
      context: ./automation-service
    restart: unless-stopped
    ports:
      - "8000:8000"

  ai-service:
    container_name: ares-ai
    build:
      context: ./ai-service # Points to the Python app directory
    restart: unless-stopped
    ports:
      - "8001:8001"

volumes:
  postgres_data:
