# config/profiles.yaml
# Order is critical. Most specific profiles first.
- profile_name: "Tier-4 Local Market Watch"
  locations: ["Bhubaneswar", "Pune"]
  roles: ["Software Engineer", "Backend Developer"]
  action: "simple_alert"
