# analytics-service/src/main/resources/application.yml
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ares_db}
    username: ${SPRING_DATASOURCE_USERNAME:ares}
    password: ${SPRING_DATASOURCE_PASSWORD:yoursecurepassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        jdbc:
          batch_size: ${HIBERNATE_BATCH_SIZE:20}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: ${REDIS_TIMEOUT:2000}
    lettuce:
      pool:
        max-active: ${REDIS_MAX_CONNECTIONS:10}
        max-idle: ${REDIS_MAX_IDLE:5}

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    me.anubhav_auth: ${LOGGING_LEVEL_APP:DEBUG}
    org.hibernate.SQL: ${LOGGING_LEVEL_SQL:INFO}
    